name: Testing A NextJS App

on: push

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install Dependencies
              run: npm ci
