name: NextJS Github Actions

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v3.8.1
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run tests